# Generated by Django 3.2.2 on 2021-05-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorAPI', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='photo_url',
            field=models.URLField(max_length=1000),
        ),
    ]
